### ISSUE TITLE
onDidReceiveBackgroundNotificationResponse callback doesn't in background

### ISSUE THREAD

**Issue by koutja** [MaikuB/flutter_local_notifications#2315]
**Describe the bug**

I ran the project from the example folder and I don't have notificationTapBackground called in the example onDidReceiveBackgroundNotificationResponse: notificationTapBackground

```dart
await flutterLocalNotificationsPlugin.initialize(
    initializationSettings,
    onDidReceiveNotificationResponse: (NotificationResponse notificationResponse) {
      notificationTapBackground(notificationResponse); // it works
    },
    onDidReceiveBackgroundNotificationResponse: notificationTapBackground,  // it doesn't work
  );
```

[notificationTapBackground](https://github.com/MaikuB/flutter_local_notifications/blob/master/flutter_local_notifications/example/lib/main.dart#L67)

**Comment by dshevchenkoo** [comment]
Same problem

**Comment by Adamteh** [comment]
You can use the getNotificationAppLaunchDetails method instead. It returns a NotificationAppLaunchDetails which contains didNotificationLaunchApp to check if the notification launched the app and the NotificationResponse.

```
 final appLaunchDetails =
      await flutterLocalNotificationsPlugin.getNotificationAppLaunchDetails();

  if (appLaunchDetails != null && appLaunchDetails.didNotificationLaunchApp) {
    if (appLaunchDetails.notificationResponse != null) {
         //Your logic
    }
  }
```

**Comment by binhtran93** [comment]
Same problem, onDidReceiveBackgroundNotificationResponse did not get called when tapping on text action.
Tapping on text action which has showsUserInterface = false did not close the notification. Does anyone know a way to do it?

**Comment by mtiendat** [comment]
Same problem

**Comment by binhtran93** [comment]
It turns out that it was my fault for not configuring the AndroidManifest file properly. The callback is getting called now

**Comment by mtiendat** [comment]
> It turns out that it was my fault for not configuring the AndroidManifest file properly. The callback is getting called now

Can you share what did you do?

**Comment by mtiendat** [comment]
Add `<receiver android:exported="false" android:name="com.dexterous.flutterlocalnotifications.ActionBroadcastReceiver" />` to your AndroidManifest. it will be work

**Comment by MaikuB** [comment]
The plugin is working as expected. I suspect the OP hasn't read the docs around the callback as the callback isn't about firing when the app is in the background. It's more on when the background isolate is used, especially for notification actions. Similarly the FCM callback has a callback that is invoked on a background isolate

**Comment by ced1check** [comment]
> You can use the getNotificationAppLaunchDetails method instead. It returns a NotificationAppLaunchDetails which contains didNotificationLaunchApp to check if the notification launched the app and the NotificationResponse.
> 
> ```
>   final appLaunchDetails =
>       await flutterLocalNotificationsPlugin.getNotificationAppLaunchDetails();
> 
>   if (appLaunchDetails != null && appLaunchDetails.didNotificationLaunchApp) {
>     if (appLaunchDetails.notificationResponse != null) {
>       //Your logic
>     }
>   }
> ```

That's the only thing that seemed to work.

> Add `<receiver android:exported="false" android:name="com.dexterous.flutterlocalnotifications.ActionBroadcastReceiver" />` to your AndroidManifest. it will be work

Didn't help in any ways and seems documented as required for actions, not for notification tap (?).

This is the same with issue https://github.com/MaikuB/flutter_local_notifications/issues/2390.

**Comment by ced1check** [comment]
FWIW, I'm using version 16.1.0, which I suppose is bugged as a similar issue is solved using 17.2.2: https://github.com/MaikuB/flutter_local_notifications/issues/2404

**Comment by MaikuB** [comment]
@ced1check did you check my response that I made back in June that was above yours at https://github.com/MaikuB/flutter_local_notifications/issues/2315#issuecomment-2157489762? From what you've said, I suspect you may have a similar misunderstanding

**Comment by ced1check** [comment]
> @ced1check did you check my response that I made back in June that was above yours at [#2315 (comment)](https://github.com/MaikuB/flutter_local_notifications/issues/2315#issuecomment-2157489762)? From what you've said, I suspect you may have a similar misunderstanding

I actually didn't understand your comment at all.

Reading the doc again, I understand it's purpose is to receive (pre-registered on iOS) actions from notifications, nothing more, nothing else. It won't get tap notification, farless its payload if any.

So why is this bug still open, if it's not a bug?

**Comment by MaikuB** [comment]
> So why is this bug still open, if it's not a bug?

Fair question and it's a combination in that I haven't gotten around doing so and in case others in the community were going to provide more complete details e.g. a link to a repo hosting a minimal app that can reproduce the issue. I will do so now to avoid further confusion. 

Note for others here that see this GitHub issue that the callback is only for notification actions that the app needs to respond to when it's not running. The "background" portion of the callback's name (`onDidReceiveBackgroundNotificationResponse`) **isn't** to do with if the app is in the background

**Comment by OktayCavus** [comment]
> Add `<receiver android:exported="false" android:name="com.dexterous.flutterlocalnotifications.ActionBroadcastReceiver" />` to your AndroidManifest. it will be work

I added this code to my manifest file, but I still cannot get an action when I press the notification while the application is in the background.

**Comment by ced1check** [comment]
> > Add `<receiver android:exported="false" android:name="com.dexterous.flutterlocalnotifications.ActionBroadcastReceiver" />` to your AndroidManifest. it will be work
> 
> I added this code to my manifest file, but I still cannot get an action when I press the notification while the application is in the background.

You need to use working around specified here: https://github.com/MaikuB/flutter_local_notifications/issues/2390.
This method is simply never called, whereas it should be called when app is in foreground!
