### ISSUE TITLE
I was told to ask you to either avoid a reference or create a plugin (I am serious :)

### ISSUE THREAD

**Issue by mark8044** [MaikuB/flutter_local_notifications#2368]
I started getting this error/warning today, out of the blue.  Maybe related to upgrade of flutter master channel SDK, as I can't remember changing anything else.

App will still launch fine

```
Package flutter_local_notifications:linux references flutter_local_notifications_linux:linux as the default plugin, but the package does not exist.
Ask the maintainers of flutter_local_notifications to either avoid referencing a default implementation via `platforms: linux: default_package: flutter_local_notifications_linux` or create a plugin named flutter_local_notifications_linux.
```

**Comment by MaikuB** [comment]
Thanks for raising. Will see if I can reproduce this but this looks odd as I don't see a difference with how this plugin references the Linux implementation compared the first-party/official plugins

**Comment by mark8044** [comment]
yes very odd, never seen such a warning before (for any plugin).  In case it matters, the master channel version I am on is:

```
Flutter 3.24.0-1.0.pre.88 • channel master • https://github.com/flutter/flutter.git
Framework • revision 43f3252c82 (5 hours ago) • 2024-07-11 13:36:55 -0700
Engine • revision 36dccf7bb2
Tools • Dart 3.6.0 (build 3.6.0-26.0.dev) • DevTools 2.37.1
```

**Comment by MaikuB** [comment]
This was resolved a patch release to the Linux package. Based on the constraints defined for the main/front-facing plugin, it should be pulled in automatically though you may need to run commands like `flutter pub upgrade`

**Comment by mark8044** [comment]
Can confirm the fix works 👍

**Comment by gnprice** [comment]
Thanks for the swift fix!

FTR it looks like this warning was introduced in https://github.com/flutter/flutter/pull/137040 .

**Comment by Megatronicus** [comment]
I'm getting this error after doing flutter upgrade, tried flutter pub upgrade, still getting these errors

Package file_picker:linux references file_picker:linux as the default plugin, but it does not provide an inline implementation.
Ask the maintainers of file_picker to either avoid referencing a default implementation via `platforms: linux: default_package: file_picker` or add an inline implementation to file_picker via `platforms: linux:` `pluginClass` or `dartPluginClass`.

Package file_picker:macos references file_picker:macos as the default plugin, but it does not provide an inline implementation.
Ask the maintainers of file_picker to either avoid referencing a default implementation via `platforms: macos: default_package: file_picker` or add an inline implementation to file_picker via `platforms: macos:` `pluginClass` or `dartPluginClass`.

Package file_picker:windows references file_picker:windows as the default plugin, but it does not provide an inline implementation.
Ask the maintainers of file_picker to either avoid referencing a default implementation via `platforms: windows: default_package: file_picker` or add an inline implementation to file_picker via `platforms: windows:` `pluginClass` or `dartPluginClass`.

Package file_picker:linux references file_picker:linux as the default plugin, but it does not provide an inline implementation.
Ask the maintainers of file_picker to either avoid referencing a default implementation via `platforms: linux: default_package: file_picker` or add an inline implementation to file_picker via `platforms: linux:` `pluginClass` or `dartPluginClass`.

Package file_picker:macos references file_picker:macos as the default plugin, but it does not provide an inline implementation.
Ask the maintainers of file_picker to either avoid referencing a default implementation via `platforms: macos: default_package: file_picker` or add an inline implementation to file_picker via `platforms: macos:` `pluginClass` or `dartPluginClass`.

Package file_picker:windows references file_picker:windows as the default plugin, but it does not provide an inline implementation.
Ask the maintainers of file_picker to either avoid referencing a default implementation via `platforms: windows: default_package: file_picker` or add an inline implementation to file_picker via `platforms: windows:` `pluginClass` or `dartPluginClass`.

Package file_picker:linux references file_picker:linux as the default plugin, but it does not provide an inline implementation.
Ask the maintainers of file_picker to either avoid referencing a default implementation via `platforms: linux: default_package: file_picker` or add an inline implementation to file_picker via `platforms: linux:` `pluginClass` or `dartPluginClass`.

Package file_picker:macos references file_picker:macos as the default plugin, but it does not provide an inline implementation.
Ask the maintainers of file_picker to either avoid referencing a default implementation via `platforms: macos: default_package: file_picker` or add an inline implementation to file_picker via `platforms: macos:` `pluginClass` or `dartPluginClass`.

Package file_picker:windows references file_picker:windows as the default plugin, but it does not provide an inline implementation.
Ask the maintainers of file_picker to either avoid referencing a default implementation via `platforms: windows: default_package: file_picker` or add an inline implementation to file_picker via `platforms: windows:` `pluginClass` or `dartPluginClass`.





Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 3.24.0-1.0.pre.217, on Microsoft Windows [Version 10.0.19045.4651], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.9.3)
[√] Android Studio (version 2024.1)
[√] VS Code (version 1.89.1)
[√] Connected device (4 available)
[√] Network resources

Android Studio Koala Feature Drop 

  file_picker: ^8.0.6

  flutter_local_notifications: ^17.2.1+2



Ran flutter pub upgrade --major-versions - still got the same error, is there another way to solve this? 

flutter pub upgrade --major-versions
Resolving dependencies... (10.8s)
Changed 2 constraints in pubspec.yaml:
  flutter_webrtc: ^0.10.7 -> ^0.11.4
  location: ^6.0.2 -> ^7.0.0
Resolving dependencies... 
Downloading packages... (7.3s)
  collection 1.18.0 (1.19.0 available)
  ffmpeg_wasm 1.0.1 (1.0.2 available)
> flutter_webrtc 0.11.4 (was 0.10.8)
  http_parser 4.0.2 (4.1.0 available)
  js 0.6.7 (0.7.1 available)
> location 7.0.0 (was 6.0.2)
> location_platform_interface 5.0.0 (was 4.0.0)
> location_web 5.0.3 (was 5.0.2)
  material_color_utilities 0.11.1 (0.12.0 available)
  web 0.5.1 (1.0.0 available)
Changed 4 dependencies!
6 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.
Package file_picker:linux references file_picker:linux as the default plugin, but it does not provide an inline implementation.
Ask the maintainers of file_picker to either avoid referencing a default implementation via `platforms: linux: default_package: file_picker` or add an inline implementation to file_picker via `platforms: linux:` `pluginClass` or `dartPluginClass`.


Package file_picker:macos references file_picker:macos as the default plugin, but it does not provide an inline implementation.
Ask the maintainers of file_picker to either avoid referencing a default implementation via `platforms: macos: default_package: file_picker` or add an inline implementation to file_picker via `platforms: macos:` `pluginClass` or `dartPluginClass`.


Package file_picker:windows references file_picker:windows as the default plugin, but it does not provide an inline implementation.
Ask the maintainers of file_picker to either avoid referencing a default implementation via `platforms: windows: default_package: file_picker` or add an inline implementation to file_picker via `platforms: windows:` `pluginClass` or `dartPluginClass`.


Package file_picker:linux references file_picker:linux as the default plugin, but it does not provide an inline implementation.
Ask the maintainers of file_picker to either avoid referencing a default implementation via `platforms: linux: default_package: file_picker` or add an inline implementation to file_picker via `platforms: linux:` `pluginClass` or `dartPluginClass`.


Package file_picker:macos references file_picker:macos as the default plugin, but it does not provide an inline implementation.
Ask the maintainers of file_picker to either avoid referencing a default implementation via `platforms: macos: default_package: file_picker` or add an inline implementation to file_picker via `platforms: macos:` `pluginClass` or `dartPluginClass`.


Package file_picker:windows references file_picker:windows as the default plugin, but it does not provide an inline implementation.
Ask the maintainers of file_picker to either avoid referencing a default implementation via `platforms: windows: default_package: file_picker` or add an inline implementation to file_picker via `platforms: windows:` `pluginClass` or `dartPluginClass`.


Package file_picker:linux references file_picker:linux as the default plugin, but it does not provide an inline implementation.
Ask the maintainers of file_picker to either avoid referencing a default implementation via `platforms: linux: default_package: file_picker` or add an inline implementation to file_picker via `platforms: linux:` `pluginClass` or `dartPluginClass`.


Package file_picker:macos references file_picker:macos as the default plugin, but it does not provide an inline implementation.
Ask the maintainers of file_picker to either avoid referencing a default implementation via `platforms: macos: default_package: file_picker` or add an inline implementation to file_picker via `platforms: macos:` `pluginClass` or `dartPluginClass`.


Package file_picker:windows references file_picker:windows as the default plugin, but it does not provide an inline implementation.
Ask the maintainers of file_picker to either avoid referencing a default implementation via `platforms: windows: default_package: file_picker` or add an inline implementation to file_picker via `platforms: windows:` `pluginClass` or `dartPluginClass`.

**Comment by gnprice** [comment]
@Megatronicus Those warning messages don't mention this plugin. Rather they're about the `file_picker` package. That means the issue you're seeing is in that other package — specifically you're seeing https://github.com/miguelpruivo/flutter_file_picker/issues/1555 .

**Comment by gnprice** [comment]
@kwabla-1 That message doesn't appear to mention this plugin.

As the message says, you should ask the maintainers of the google_api_headers plugin to resolve those warnings.

**Comment by rmahmadkhan** [comment]
I am still getting this error on Flutter `3.27.1`.


```
Package stream_video_push_notification:android references stream_video_push_notification:android as the default plugin, but it does not provide an inline implementation.
Ask the maintainers of stream_video_push_notification to either avoid referencing a default implementation via `platforms: android: default_package: stream_video_push_notification` or add an inline implementation to stream_video_push_notification via `platforms: android:` `pluginClass` or `dartPluginClass`.

Package stream_video_push_notification:android references stream_video_push_notification:android as the default plugin, but it does not provide an inline implementation.
Ask the maintainers of stream_video_push_notification to either avoid referencing a default implementation via `platforms: android: default_package: stream_video_push_notification` or add an inline implementation to stream_video_push_notification via `platforms: android:` `pluginClass` or `dartPluginClass`.

Package stream_video_push_notification:android references stream_video_push_notification:android as the default plugin, but it does not provide an inline implementation.
Ask the maintainers of stream_video_push_notification to either avoid referencing a default implementation via `platforms: android: default_package: stream_video_push_notification` or add an inline implementation to stream_video_push_notification via `platforms: android:` `pluginClass` or `dartPluginClass`.

Package stream_video_push_notification:android references stream_video_push_notification:android as the default plugin, but it does not provide an inline implementation.
Ask the maintainers of stream_video_push_notification to either avoid referencing a default implementation via `platforms: android: default_package: stream_video_push_notification` or add an inline implementation to stream_video_push_notification via `platforms: android:` `pluginClass` or `dartPluginClass`.
```

**Comment by Levi-Lesches** [comment]
@rmahmadkhan please read the error you posted. It doesn't refer to this plugin but rather `stream_video_push_notification`. Please file an issue on that package instead

**Comment by aaravprimeYT** [comment]
Hi, whenever I try to do anything in the terminal such as pub get or pub upgrade or even run my app I keep getting this error.

`C:\Users\HP_Demo\OneDrive\Desktop\flutter_windows_3.27.2-stable\flutter\bin\flutter.bat --no-color pub upgrade
Resolving dependencies...
Downloading packages...
  async 2.11.0 (2.12.0 available)
  boolean_selector 2.1.1 (2.1.2 available)
  cached_network_image 3.3.1 (3.4.1 available)
  cached_network_image_platform_interface 4.0.0 (4.1.1 available)
  cached_network_image_web 1.2.0 (1.3.1 available)
  characters 1.3.0 (1.4.0 available)
  clock 1.1.1 (1.1.2 available)
  collection 1.19.0 (1.19.1 available)
  fake_async 1.3.1 (1.3.2 available)
  flutter_cache_manager 3.3.1 (3.4.1 available)
  flutter_polyline_points 1.0.0 (2.1.0 available)
  flutter_svg 2.0.9 (2.0.17 available)
  google_api_headers 1.6.0 (4.3.2 available)
  google_fonts 4.0.4 (6.2.1 available)
  http 0.13.6 (1.2.2 available)
  intl 0.19.0 (0.20.1 available)
  leak_tracker 10.0.7 (10.0.8 available)
  leak_tracker_flutter_testing 3.0.8 (3.0.9 available)
  matcher 0.12.16+1 (0.12.17 available)
  material_color_utilities 0.11.1 (0.12.0 available)
  meta 1.15.0 (1.16.0 available)
  package_info_plus 4.2.0 (8.1.3 available)
  package_info_plus_platform_interface 2.0.1 (3.0.2 available)
  path 1.9.0 (1.9.1 available)
  petitparser 6.0.2 (6.1.0 available)
  rxdart 0.26.0 (0.28.0 available)
  source_span 1.10.0 (1.10.1 available)
  stack_trace 1.12.0 (1.12.1 available)
  stream_channel 2.1.2 (2.1.4 available)
  string_scanner 1.3.0 (1.4.1 available)
  term_glyph 1.2.1 (1.2.2 available)
  test_api 0.7.3 (0.7.4 available)
  vector_graphics 1.1.10+1 (1.1.15 available)
  vector_graphics_codec 1.1.10+1 (1.1.13 available)
  vector_graphics_compiler 1.1.10+1 (1.1.16 available)
  vm_service 14.3.0 (15.0.0 available)
No dependencies changed.
36 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.
Package google_api_headers:ios references google_api_headers:ios as the default plugin, but it does not provide an inline implementation.
Ask the maintainers of google_api_headers to either avoid referencing a default implementation via `platforms: ios: default_package: google_api_headers` or add an inline implementation to google_api_headers via `platforms: ios:` `pluginClass` or `dartPluginClass`.

Package google_api_headers:linux references google_api_headers:linux as the default plugin, but it does not provide an inline implementation.
Ask the maintainers of google_api_headers to either avoid referencing a default implementation via `platforms: linux: default_package: google_api_headers` or add an inline implementation to google_api_headers via `platforms: linux:` `pluginClass` or `dartPluginClass`.

Package google_api_headers:macos references google_api_headers:macos as the default plugin, but it does not provide an inline implementation.
Ask the maintainers of google_api_headers to either avoid referencing a default implementation via `platforms: macos: default_package: google_api_headers` or add an inline implementation to google_api_headers via `platforms: macos:` `pluginClass` or `dartPluginClass`.

Package google_api_headers:windows references google_api_headers:windows as the default plugin, but it does not provide an inline implementation.
Ask the maintainers of google_api_headers to either avoid referencing a default implementation via `platforms: windows: default_package: google_api_headers` or add an inline implementation to google_api_headers via `platforms: windows:` `pluginClass` or `dartPluginClass`.

Package google_api_headers:ios references google_api_headers:ios as the default plugin, but it does not provide an inline implementation.
Ask the maintainers of google_api_headers to either avoid referencing a default implementation via `platforms: ios: default_package: google_api_headers` or add an inline implementation to google_api_headers via `platforms: ios:` `pluginClass` or `dartPluginClass`.

Package google_api_headers:linux references google_api_headers:linux as the default plugin, but it does not provide an inline implementation.
Ask the maintainers of google_api_headers to either avoid referencing a default implementation via `platforms: linux: default_package: google_api_headers` or add an inline implementation to google_api_headers via `platforms: linux:` `pluginClass` or `dartPluginClass`.

Package google_api_headers:macos references google_api_headers:macos as the default plugin, but it does not provide an inline implementation.
Ask the maintainers of google_api_headers to either avoid referencing a default implementation via `platforms: macos: default_package: google_api_headers` or add an inline implementation to google_api_headers via `platforms: macos:` `pluginClass` or `dartPluginClass`.

Package google_api_headers:windows references google_api_headers:windows as the default plugin, but it does not provide an inline implementation.
Ask the maintainers of google_api_headers to either avoid referencing a default implementation via `platforms: windows: default_package: google_api_headers` or add an inline implementation to google_api_headers via `platforms: windows:` `pluginClass` or `dartPluginClass`.

Package google_api_headers:ios references google_api_headers:ios as the default plugin, but it does not provide an inline implementation.
Ask the maintainers of google_api_headers to either avoid referencing a default implementation via `platforms: ios: default_package: google_api_headers` or add an inline implementation to google_api_headers via `platforms: ios:` `pluginClass` or `dartPluginClass`.

Package google_api_headers:linux references google_api_headers:linux as the default plugin, but it does not provide an inline implementation.
Ask the maintainers of google_api_headers to either avoid referencing a default implementation via `platforms: linux: default_package: google_api_headers` or add an inline implementation to google_api_headers via `platforms: linux:` `pluginClass` or `dartPluginClass`.

Package google_api_headers:macos references google_api_headers:macos as the default plugin, but it does not provide an inline implementation.
Ask the maintainers of google_api_headers to either avoid referencing a default implementation via `platforms: macos: default_package: google_api_headers` or add an inline implementation to google_api_headers via `platforms: macos:` `pluginClass` or `dartPluginClass`.

Package google_api_headers:windows references google_api_headers:windows as the default plugin, but it does not provide an inline implementation.
Ask the maintainers of google_api_headers to either avoid referencing a default implementation via `platforms: windows: default_package: google_api_headers` or add an inline implementation to google_api_headers via `platforms: windows:` `pluginClass` or `dartPluginClass`.
`

does anyone know how to fix this?

**Comment by MaikuB** [comment]
@aaravprimeYT that doesn't have to do this plugin but to do with `google_api_headers`. As there's been a number of comments/questions to do with other plugins, I'll lock this thread. This isn't something I normally do but helps reduce everyone who has participated in this thread from getting notifications about unrelated issues
