### ISSUE TITLE
onSelectNotification code not being called when a notification is tapped and the application is not running

### ISSUE THREAD

**Issue by GroovinChip** [MaikuB/flutter_local_notifications#93]
It works perfectly while the app is running, but when the application is closed the function is not called.

The code can be found here [https://github.com/GroovinChip/CallManager/blob/dev/lib/HomeScreen.dart](url)

I can't provide a stacktrace because the issue only occurs while the app is not running.

If you'd be so kind as to provide quick assistance, I'd really appreciate it - I had to pull a crucial feature from production due to this bug.

Thanks!

**Comment by MaikuB** [comment]
Which platforms are you seeing this issue on? Have you also tried running the example app as last I checked, it works fine when the app isn't running and will navigate to the details screen upon launching

**Comment by GroovinChip** [comment]
I'm using this on Android. My personal phone is a Pixel XL 2016 running Android Pie 9.0, but the issue is reproducible on any Android version.

I've not tried running your example, I've just carefully gone through your README.

**Comment by MaikuB** [comment]
It'd be good if you could try running the example and let me know it goes. After that, what would be worth trying as well (as it's not something I can get to ATM) is to modify the example so it triggers the call number function and see if that works

**Comment by MaikuB** [comment]
Just to add with the last part around pulling the call number package to call it, it'd be good if you could fork my repo

**Comment by MaikuB** [comment]
I believe if you open your Android head project via Android studio too then you'd be able to step into the code of the notifications and call number package. This may or may not require you to reference a local copy

**Comment by MaikuB** [comment]
Was able to take a look at this.

1. I was unable to build your app as the following error occurred

```
Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.
FAILURE: Build failed with an exception.
* Where:
Build file '/Users/michaelbui/Projects/CallManager-dev/android/app/build.gradle' line: 17
* What went wrong:
A problem occurred evaluating project ':app'.
> java.net.URISyntaxException: Illegal character in opaque part at index 2: C:\Users\groov\Flutter_Projects\call_manager\key.properties
```
2. I tested out what I suggested in the example and it was working fine on my phone (Pixel 2 XL on Android P) and an Android O emulator but it only works when the permissions to make calls had been accepted beforehand. This happened when the app was running and not running too. That is, even if the app was running, upon granting the app permissions to make a call, it wouldn't proceed to make a call. This doesn't seem to be related to the notifications plugin as it also happened even if I wired up a button to call `await CallNumber().callNumber(...)`

**Comment by GroovinChip** [comment]
Hey, sorry! I was at work all day and wasn't able to get to this until now. What happens if you try the url_launcher package and use the "tel:" string?

**Comment by MaikuB** [comment]
I haven't been able to check re: "tel:" but as mentioned, I can run your app. Would need you to fork the example from this repo as I don't actually have anything to reproduce your problem. As suggested above, I'd advise stepping through the code of the plugins as well

**Comment by MaikuB** [comment]
Also just as an update, I've tried the url_launcher and it was fine

**Comment by GroovinChip** [comment]
Okay I'll do that today and report back, thanks so much

**Comment by GroovinChip** [comment]
It works fine in your app, but not in mine. So weird. I think maybe it has to do with how I implemented your package?

**Comment by MaikuB** [comment]
At a glance it doesn't look like there's anything wrong but yeah sorry I don't know what's going on given I can't reproduce it. I believe I suggested above you can debug the plugin code, and perhaps you'll be able to find what's going on and submit a PR if you find what it is. Having only had brief look at your app, I feel that what you're after with making phone calls would be better achieved once the work to do custom actions #17 via headless dart execution is done. Currently, even if it did work it will still launch your app.

I know one difference between the example app and your one is that the callback is in the main.dart file. It's a longshot but perhaps try moving your home screen to the main.dart file and see if it makes a difference as well?

**Comment by GroovinChip** [comment]
Interesting idea about main.dart, I'll give that a shot. I still haven't figured out debugging packages, so I'll try the former option first.

**Comment by GroovinChip** [comment]
Are you sure this would help? I just remembered that the problem only occurs when the app is not running, meaning I'm not going to be able to step through the code, right?

**Comment by MaikuB** [comment]
From what I remember logcat should still show messages even when the app isn't running as I ran into issues that I had to fix when developing the plugin around rescheduling notifications on a reboot. Shouldn't take that much time for you to see if you have Android studio installed already

**Comment by GroovinChip** [comment]
I'll give it a shot again, but I've looked at the logcat in AS previously for this issue and there was nothing. Thanks so much for your patience and help, I really appreciate it! I'll let you know what happens.

**Comment by MaikuB** [comment]
Likewise! Would love to help hard without being able to reproduce it myself :S

**Comment by GroovinChip** [comment]
:)

Yeah, the reason you can't build the project is because my backend is Firebase, so you'd need a google-services.json file, which I obviously don't include in the repo, and also have a keystore set up.

**Comment by GroovinChip** [comment]
OK, putting the home screen widget in main.dart doesn't help because the 'home' property of the MaterialApp is the login page. I'll just have to step through the code. What exactly is the 'Android Head' you meantioned? Do I just import your whole package into my project?

**Comment by MaikuB** [comment]
Flutter apps still consist of normal iOS and Android projects that can be obtained in xCode and Android Studio respectively. This allows you to run and debug the code on the native side (Objective C/Swift for iOS, Java/Kotlin for Android). These are the head projects I'm referring to. If you're using VS code, then if you were to right click on the android folder of your Flutter app, there's an option to open the Android head project in Android Studio. Alternatively, I think the other option was to run Android Studio and select to import/open an existing Android project, then select build.gradle file under /android/app relative to the root of your Flutter app

**Comment by vladaman** [comment]
I am experiencing same issue on Android. I think it has something to do with null context.

_firebaseMessaging.onResume() is called after user taps notification in the notification bar. Yet when I check for context it's null here. The App has not been rendered or initialized. Therefore I cannot navigate user further.
```dart
_firebaseMessaging.configure(
    onResume: (Map<String, dynamic> message) {
    new MaterialPageRoute(builder: (context) => new NextScreen()), // context here is null
})
````

**Comment by MaikuB** [comment]
Sorry but it's not clear how this relates to this plugin given your code snippet involves firebase messaging so it seems like it'd be more appropriate for you to post your issue on the Flutter repository

**Comment by DevarshRanpara** [comment]
Facing same issue in my Android project.
`onSelectNotification` callback never called by system.

**Comment by MaikuB** [comment]
@DevarshRanpara please provide a minimal app that can reproduce the problem

**Comment by DevarshRanpara** [comment]
@MaikuB pelase refer this [547](https://github.com/MaikuB/flutter_local_notifications/issues/547) i have added more details in this issue.

**Comment by diegobarle** [comment]
It might not be your case, but when opening the app from the notification you need to check with the plugin if a notification opened the app. So basically in the first screen, after initialising the `FlutterLocalNotificationsPlugin`, check `didNotificationLaunchApp` and if true call your `onSelectNotification` method:
```
    final notificationAppLaunchDetails = await flutterLocalNotificationsPlugin.getNotificationAppLaunchDetails();
    if (notificationAppLaunchDetails?.didNotificationLaunchApp ?? false) {
      await onSelectNotification(notificationAppLaunchDetails.payload);
    }
```

**Comment by savitashukla** [comment]
final notificationAppLaunchDetails = await flutterLocalNotificationsPlugin.getNotificationAppLaunchDetails();
    if (notificationAppLaunchDetails?.didNotificationLaunchApp ?? false) {
      await onSelectNotification(notificationAppLaunchDetails.payload);
    }
    This is working fine in my project  Lunch Time select Notification
